"""Add modified_by_user_id

Revision ID: 8e80569d5013
Revises: 14e3c86ac1a3
Create Date: 2020-08-18 06:38:10.069339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e80569d5013'
down_revision = '14e3c86ac1a3'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_modified_by_user_id_users'), 'users', ['modified_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_modified_by_user_id_users'), type_='foreignkey')
        batch_op.drop_column('modified_by_user_id')

    # ### end Alembic commands ###
