"""add server_id to hublog

Revision ID: 84443a4325d5
Revises: 6fab8ab551d5
Create Date: 2020-11-22 07:13:23.880817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84443a4325d5'
down_revision = '6fab8ab551d5'
branch_labels = ()
depends_on = None


def upgrade():
    with op.batch_alter_table('hub_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hub_log', schema=None) as batch_op:
        batch_op.drop_column('server_id')
    # ### end Alembic commands ###
