"""Change topic's and forum's creator username for display_name

Revision ID: 34b4f4dc375c
Revises: 3c1a7ce32104
Create Date: 2021-03-21 06:25:26.711175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34b4f4dc375c'
down_revision = '3c1a7ce32104'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_user_display_name', sa.String(length=255), nullable=True))
        batch_op.drop_column('last_post_username')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_display_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('username')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_display_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('user_display_name')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('user_display_name')

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_username', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('last_post_user_display_name')
    # ### end Alembic commands ###
