"""File uploads

Revision ID: d087ef70bb22
Revises: 8363ff3f6884
Create Date: 2022-08-24 13:20:31.718037

"""
from alembic import op
import sqlalchemy as sa
import flaskbb


# revision identifiers, used by Alembic.
revision = 'd087ef70bb22'
down_revision = '8363ff3f6884'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', flaskbb.utils.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('current_name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datetime'], ['users.id'], name=op.f('fk_uploaded_files_datetime_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploaded_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'datetime', name=op.f('pk_uploaded_files'))
    )
    
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_folder_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('uploaded_file_max_length', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('uploaded_file_max_length')
        batch_op.drop_column('upload_folder_limit')

    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
