"""Community Rating

Revision ID: 61506a4d9859
Revises: d087ef70bb22
Create Date: 2022-08-24 13:28:42.888148

"""
from alembic import op
import sqlalchemy as sa
import flaskbb


# revision identifiers, used by Alembic.
revision = '61506a4d9859'
down_revision = 'd087ef70bb22'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('datetime', flaskbb.utils.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_community_rating_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_rating'))
    )
    with op.batch_alter_table('community_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('community_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_rating_user_id'))

    op.drop_table('community_rating')
    # ### end Alembic commands ###
