"""Add forum.discord_report_channel

Revision ID: ee45d2c3932e
Revises: d6e71550f44b
Create Date: 2023-01-13 09:57:35.142530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee45d2c3932e'
down_revision = 'd6e71550f44b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_report_channel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('discord_report_posts', sa.Boolean(), nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_message_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('discord_message_id')

    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('discord_report_posts')
        batch_op.drop_column('discord_report_channel')

    # ### end Alembic commands ###
