"""Update permissions columns

Revision ID: e12f4e291c8c
Revises: ee45d2c3932e
Create Date: 2024-03-29 15:32:14.518020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12f4e291c8c'
down_revision = 'ee45d2c3932e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
