"""add hub log

Revision ID: 6fab8ab551d5
Revises: a0de32339e79
Create Date: 2020-11-21 15:54:10.910422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flaskbb

# revision identifiers, used by Alembic.
revision = '6fab8ab551d5'
down_revision = 'a0de32339e79'
branch_labels = ()
depends_on = None


def upgrade():
    op.create_table('hub_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', flaskbb.utils.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hub_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hub_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hub_log')
    # ### end Alembic commands ###
