"""add hub permissions

Revision ID: ba063d7df9ca
Revises: 8e80569d5013
Create Date: 2020-10-04 01:41:41.514412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba063d7df9ca'
down_revision = '8e80569d5013'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dragon_additional', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('dragon_base', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('eos_additional', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('eos_base', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('onyx_additional', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('onyx_base', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('onyx_base')
        batch_op.drop_column('onyx_additional')
        batch_op.drop_column('eos_base')
        batch_op.drop_column('eos_additional')
        batch_op.drop_column('dragon_base')
        batch_op.drop_column('dragon_additional')

    # ### end Alembic commands ###
