"""Make topic's creator username nullable

Revision ID: 3c1a7ce32104
Revises: 84443a4325d5
Create Date: 2021-03-21 06:08:06.678130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c1a7ce32104'
down_revision = '84443a4325d5'
branch_labels = ()
depends_on = None


def upgrade():
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
