"""add whitelist

Revision ID: 55daac662f22
Revises: 8e509faa7cfd
Create Date: 2025-05-24 00:59:06.641274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55daac662f22'
down_revision = '8e509faa7cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'hub_permissions',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.add_column('servers', sa.Column('whitelist_channel', sa.String(length=255), nullable=False))
    op.alter_column('servers', 'configs_exclude',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_base_access_titles',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_full_access_titles',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_role_to_group',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'discord_role_to_group',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'discord_full_access_titles',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'discord_base_access_titles',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'configs_exclude',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.drop_column('servers', 'whitelist_channel')
    op.alter_column('groups', 'hub_permissions',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    # ### end Alembic commands ###
