"""Add hub_permissions JSON field to Group

Revision ID: 7613f3027fd0
Revises: e12f4e291c8c
Create Date: 2025-05-23 16:19:52.743779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7613f3027fd0'
down_revision = 'e12f4e291c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('hub_permissions', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.drop_column('groups', 'malachite_base')
    op.drop_column('groups', 'onyx_additional')
    op.drop_column('groups', 'onyx_management')
    op.drop_column('groups', 'malachite_additional')
    op.drop_column('groups', 'onyx_base')
    op.drop_column('groups', 'malachite_management')
    op.alter_column('hub_log', 'message',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('plugin_store', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('posts', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('settings', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('settingsgroup', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'notes',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'signature',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'signature',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('users', 'notes',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('settingsgroup', 'description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('settings', 'description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('plugin_store', 'description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('hub_log', 'message',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.add_column('groups', sa.Column('malachite_management', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('onyx_base', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('malachite_additional', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('onyx_management', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('onyx_additional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('malachite_base', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('groups', 'hub_permissions')
    # ### end Alembic commands ###
