"""Move servers config to DB

Revision ID: 8e509faa7cfd
Revises: 7613f3027fd0
Create Date: 2025-05-23 17:16:48.571923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e509faa7cfd'
down_revision = '7613f3027fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('dream_maker_binary', sa.String(length=255), nullable=False),
    sa.Column('dme_name', sa.String(length=255), nullable=False),
    sa.Column('configs_path', sa.String(length=255), nullable=False),
    sa.Column('configs_exclude', sa.JSON(), nullable=True),
    sa.Column('logs_path', sa.String(length=255), nullable=False),
    sa.Column('discord_full_access_titles', sa.JSON(), nullable=True),
    sa.Column('discord_base_access_titles', sa.JSON(), nullable=True),
    sa.Column('discord_role_to_group', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers'))
    )
    op.create_table('server_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(length=255), nullable=False),
    sa.Column('what', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_links_server_id_servers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_links'))
    )
    op.alter_column('groups', 'hub_permissions',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'hub_permissions',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.drop_table('server_links')
    op.drop_table('servers')
    # ### end Alembic commands ###
