"""add whitelist part two

Revision ID: c41434de5b38
Revises: 55daac662f22
Create Date: 2025-05-24 01:42:25.382383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c41434de5b38'
down_revision = '55daac662f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(length=255), nullable=False),
    sa.Column('ckey', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('forum', 'channel', name='source_type'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='whitelist_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whitelist_applications'))
    )
    op.alter_column('groups', 'hub_permissions',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('servers', 'configs_exclude',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_base_access_titles',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_full_access_titles',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('servers', 'discord_role_to_group',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'discord_role_to_group',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'discord_full_access_titles',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'discord_base_access_titles',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('servers', 'configs_exclude',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.alter_column('groups', 'hub_permissions',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.drop_table('whitelist_applications')
    # ### end Alembic commands ###
